name: "Urbanrunic Corp"
description: "Site containing information on Urbanrunic Services, Blog and Contact"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
