name: "Urbanrunic Corp"
description: "Site containing information on Urbanrunic Services, Blog and Contact"

url: "urbanrunic.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
