name: "Urbanrunic Corp"
description: "Site containing information on Urbanrunic Services, Blog and Contact"

url: "http://urbanrunic.github.io/"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
